### ISSUE TITLE
bug: unable to upload files (http-framework)

### ISSUE THREAD

**Issue by treboryx** [skyra-project/archid-components#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Interaction fails when uploading files

### Steps To Reproduce

Code to reproduce: 

```ts
const file = await getImgBuffer(); // getting any image buffer
const embed = new EmbedBuilder().setImage('attachment://image.png').toJSON(); // embed builder from @discordjs/builders

return this.message({
	files: [{ name: 'image.png', data: file }],
	attachments: [{ id: '0', description: `image desc`, filename: 'image.png' }],
	embeds: [embed]
});
```

### Expected behavior

Send an embed with an image that was attached

### Screenshots

Interaction simply fails

**Comment by Bobby-McBobface** [comment]
I have the same issue.
