### ISSUE TITLE
bug: body is ignored when yield this.defer() is used

### ISSUE THREAD

**Issue by treboryx** [skyra-project/archid-components#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The body is ignored when you call `yield this.defer()`

only the files are passed

### Steps To Reproduce

```ts
yield this.defer();

this.message({ files: [], content: 'test'}); // content is ignored, files are passed
```

### Expected behavior

content to be passed

**Comment by kyranet** [comment]
It's not ignored, it's just an invalid payload. I need to make an [`updateMessage`](https://github.com/skyra-project/iriss/blob/3763e8bc6883efed7fd39e1ef6a0a1eced196b58/src/commands/suggest.ts#L273-L275) method for this 😅
