### ISSUE TITLE
bug: wrong documentation in http-framework

### ISSUE THREAD

**Issue by Bobby-McBobface** [skyra-project/archid-components#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

http-framework/src/lib/interactions/utils/util.ts L170
```js
	// `generator.next(...)` call. As such, the following code works:
	//
	//     yield this.defer(); // null
	//     yield this.message({ content: 'Hello There' }); // APIMessage
	//     yield this.message({ content: 'General Kenobi!' }); // APIMessage
```

However, this errors.

This is because yielding/returning `this.message` returns `{ type: 4, data, files }` (http-framework/src/lib/structures/Command.ts L88)

However, in http-framework/src/lib/interactions/utils/util.ts L192 & L 187,
`await patchMessage(interaction, result.value);` is passed into `patchMessage`. `patchMessage` accepts `{ files, ...body }` as parameters, but the `...body` unpacks `this.message({ content: 'Hello There' })`'s return value into `{ type: 4, data: { content: 'Hello There' } }`, which the API does not accept.

### Steps To Reproduce

```js
yield this.defer();
return this.message({ content: "Hello world!" })
```

### Expected behavior

It sends "Hello world!", however it currently errors

**Comment by kyranet** [comment]
I have meant to port Iriss's `updateMessage` protected method for a while, but I didn't get to it.

Do you want to open a PR fixing this?
